### ISSUE TITLE
Several accounts possible?

### ISSUE THREAD

**Issue by tobiasBora** [a-sk/node-imapnotify#23]
Hello,

First thank you for this great tool. I'd like to know, do you provide a way to have multiple accounts, or should I run several instances on several configuration files?

Thanks.

**Comment by mudrd8mz** [comment]
From looking at the code, multiple accounts do not seem supported. I ended up having multiple instances running, each with their own config file.

**Comment by keithbowes** [comment]
> From looking at the code, multiple accounts do not seem supported. I ended up having multiple instances running, each with their own config file.

It's odd that the NodeJS version doesn't allow multiple accounts in the same file like [the Go version](https://gitlab.com/shackra/goimapnotify) does:
```json
 [
  {
    account1
  },
  {
    account2
  },
  …
 ]
```

However, if you try that in versions 2.3.16+ of the Go version, you'll get an error, because that was changed slightly due to YAML support (it now defaults to a YAML config file but you can specify a JSON config file via a command-line option):
```json
{
  "configurations": [
    {
      account1
    },
    {
      account2
    },
    …
  ]
}
```

**Comment by ncrosty58** [comment]
This project hasn't had a commit in 7+ years, so if you're still looking for a maintained alternative: I just released [imap-idle-hook](https://github.com/ncrosty58/imap-idle-hook), a minimal Docker container that does exactly this. Multiple accounts are a first-class citizen — configure them via a mounted YAML file or `ACCOUNT_N_*` env vars:

```yaml
# accounts.yaml
webhook:
  url: https://your-app.example.com/hooks/mail

accounts:
  - email: support@example.com
    password: secret
    host: imap.example.com
  - email: info@example.com
    password: secret
    host: imap.example.com
```

```yaml
# docker-compose.yml
services:
  imap-idle-hook:
    image: ghcr.io/ncrosty58/imap-idle-hook:latest
    restart: unless-stopped
    volumes:
      - ./accounts.yaml:/config/accounts.yaml:ro
```

Fires a webhook on new mail per account. No polling.
